services:
  booking_back_service:
    container_name: "booking_back"
    build:
      context: .
    env_file:
      - .env
    # ports:
    #   - "7777:8000"
    networks:
      - myNetwork
    # depends_on:
    #   booking_db:
    #     condition: service_healthy

  booking_celery_worker_service:
    container_name: "booking_celery_worker"
    build:
      context: .
    env_file:
      - .env
    networks:
      - myNetwork
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO -B"

  booking_celery_beat_service:
    container_name: "booking_celery_beat"
    build:
      context: .
    env_file:
      - .env
    networks:
      - myNetwork
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

  # booking_db:
  #   container_name: "booking_db"
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: username
  #     POSTGRES_PASSWORD: 12345678
  #     POSTGRES_DB: booking
  #   networks:
  #     - myNetwork
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U username -d booking"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

networks:
  myNetwork:
    external: true
