services:
  booking_back_service:
    container_name: "booking_back"
    build:
      context: .
    env_file:
      - .env
    # ports:
    #   - "7777:8000"
    networks:
      - myNetwork

  booking_celery_worker_service:
    container_name: "booking_celery_worker"
    build:
      context: .
    env_file:
      - .env
    networks:
      - myNetwork
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO -B"

  booking_celery_beat_service:
    container_name: "booking_celery_beat"
    build:
      context: .
    env_file:
      - .env
    networks:
      - myNetwork
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks:
  myNetwork:
    external: true
