"""Made hotel title unique

Revision ID: cb0d2865f835
Revises: 5a904717c891
Create Date: 2025-08-11 19:30:13.146892

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb0d2865f835"
down_revision: Union[str, None] = "5a904717c891"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "hotels", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotels", type_="unique")
    # ### end Alembic commands ###
