"""Made hotel titles unique

Revision ID: 443886e3bf05
Revises: cb0d2865f835
Create Date: 2025-08-11 19:36:46.452834

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "443886e3bf05"
down_revision: Union[str, None] = "cb0d2865f835"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "rooms", ["title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rooms", type_="unique")
    # ### end Alembic commands ###
